name: mms-faetar
channels:
  - huggingface
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - datasets
  - librosa
  - evaluate
  - pytorch-cuda
  - pytorch
  - jiwer
  - transformers
  - accelerate
