name: faetar-dev-kit
channels:
  - huggingface
  - pytorch
  - nvidia
  - conda-forge
  - sdrobert
  - nodefaults
dependencies:
  - datasets
  - librosa
  - evaluate
  - pytorch-cuda=11.8
  - pytorch=2.3.*
  - jiwer>=3
  - transformers
  - accelerate
  - pyctcdecode
  - diskcache
  - pip:
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git"
    - "git+https://github.com/sdrobert/kenlm"
    - confidence_intervals
variables:
  PYTHONUTF8: 1
